### PR TITLE
Revert items to inventory manually in 2.2.4+

### PR DESCRIPTION
**Pull request by marabiat**
Fix issue where a failed order in Magento versions 2.2.4 and newer would not return the items to the stock.

### CODE REVIEW

**Comment by DeyaZ88** [comment]
Code Accepted

**Comment by marabiat** [comment]
An issue was found when deploying the code to the Magento 2.3 instance. It has been traced back to the enabling of the Multiple Source Inventory feature. This feature installs a module that registers an interceptor that changes the logic of the `revertProductsSale` call and has it returning `true` for success rather than an array of the reverted items. 

The feature is installed and enabled automatically if Magento 2 was installed via composer (as per [this guide](https://devdocs.magento.com/guides/v2.3/install-gde/composer.html)). 

@DeyaZ88 if you would so kindly review the code again, thanks.

**Comment by DeyaZ88** [comment]
Code accepted.

**Comment by marabiat** [comment]
QA approved.

**Review by Reem-Hamdan — APPROVED** [review]

**Pull request merged**
